# Generated by Django 6.1 on 2026-08-15 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.DateField(default=datetime.date(2026, 8, 1)),
            preserve_default=False,
        ),
    ]
