# Generated by Django 6.1 on 2026-08-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='unique_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
